"""Contracts and typed payloads for plan-agent integrations."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from pydantic import BaseModel, Field

# Session keys written by plan_agent (read these in tools/callbacks if needed).
SESSION_BASE_INSTRUCTION = "plan_agent_base_instruction"
SESSION_SKILL_CANDIDATES = "plan_agent_skill_candidates"
SESSION_SELECTED_SKILL = "plan_agent_selected_skill"
SESSION_REGISTRY_ATTEMPTS = "plan_agent_registry_attempts"
SESSION_REGISTRY_LAST_QUERY = "plan_agent_registry_last_query"


@dataclass(frozen=True)
class SkillCandidate:
    """One routable skill from Zep (or your catalog), surfaced to the router LLM."""

    id: str
    title: str = ""
    summary: str = ""
    body: str = ""
    metadata: dict[str, Any] | None = None

    def as_state_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "summary": self.summary,
            "body": self.body,
            "metadata": dict(self.metadata or {}),
        }


class ZepRetrievalRequest(BaseModel):
    """Typed request object generated by your registry LLM core."""

    query: str = Field(..., min_length=1, description="Main query sent to Zep.")
    top_k: int = Field(
        default=8,
        ge=1,
        le=50,
        description="How many nodes/chunks to retrieve.",
    )
    scope: str | None = Field(
        default=None,
        description="Optional scope key (workspace, collection, graph, etc.).",
    )
    filters: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured filters used by your Zep adapter.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra retrieval hints that your Zep adapter can consume.",
    )


class ZepRegistryPlan(BaseModel):
    """JSON envelope expected from the registry-generation LLM call."""

    request: ZepRetrievalRequest
    reason: str = Field(default="", description="Optional model rationale for debugging.")


class LangfusePromptProvider(Protocol):
    """Load compiled prompt text from Langfuse (tracing stays in your client)."""

    async def load_text_prompt(self, name: str, *, label: str | None = None) -> str:
        """Return the system-style instruction text for this agent."""


class ZepRegistryCore(Protocol):
    """Your LLM wrapper that generates JSON for `ZepRegistryPlan`."""

    async def generate_registry_json(
        self,
        *,
        prompt: str,
        user_message: str,
        attempt: int,
        previous_error: str | None = None,
    ) -> str:
        """Return strict JSON text parseable as `ZepRegistryPlan`."""


class ZepSkillCatalog(Protocol):
    """Zep adapter that executes one retrieval request and maps to skill candidates."""

    async def retrieve_candidates(
        self,
        request: ZepRetrievalRequest,
    ) -> list[SkillCandidate]:
        """Run one Zep retrieval call using the generated request."""


class SkillRouter(Protocol):
    """Router LLM: pick exactly one skill id from candidates."""

    async def pick_skill_id(
        self,
        user_message: str,
        candidates: Sequence[SkillCandidate],
    ) -> str:
        """Return the winning `SkillCandidate.id` (must exist in `candidates`)."""


@runtime_checkable
class PlanAgentDeps(Protocol):
    """Bundle you implement: Langfuse + registry core + Zep + router."""

    langfuse: LangfusePromptProvider
    registry_core: ZepRegistryCore
    zep: ZepSkillCatalog
    router: SkillRouter
