# SPDX-License-Identifier: Apache-2.0
"""Shared agent core abstractions."""

from imp_agent_core.agents.agent_core.adk import (
    AdkA2aExecutor,
    ConfiguredA2aExecutor,
)
from imp_agent_core.agents.agent_core.inference import (
    InferenceProviderLlmAdapter,
    default_instruction_prompt_name,
    load_agent_instruction,
)
from imp_agent_core.agents.agent_core.routing import (
    AgentBackendType,
    AgentDescriptor,
    AgentHealthStatus,
    AgentInvocationResult,
    AgentResolver,
    BaseAgentHandle,
    DynamicAgentRegistry,
    HostOrchestrator,
    LocalA2AHandle,
    RemoteA2AHandle,
    SkillDescriptor,
    get_global_agent_registry,
    register_agent_package,
    reset_global_agent_registry,
)
from imp_agent_core.agents.agent_core.sub_agent_invoke import (
    DEFAULT_SUB_AGENT_TOOL_INSTRUCTION,
    SubAgentInvocationPolicy,
    SubAgentInvoker,
    SubAgentToolConfig,
    make_sub_agent_tool,
)

from imp_agent_core.agents.agent_core.a2a import (
    A2A_RUNTIME_ENV,
    A2AFlowResult,
    A2aRuntime,
    LocalA2aAgent,
    OrchestrationMode,
    build_agent_card_from_yaml,
    build_get_task_request,
    build_local_a2a_agent,
    build_message_payload,
    build_post_request,
    configured_a2a_runtime,
    extract_task_id,
    local_a2a_orchestration_mode,
    run_local_a2a_orchestration,
    set_local_a2a_orchestration_mode,
)

__all__ = [
    "A2AFlowResult",
    "A2A_RUNTIME_ENV",
    "A2aRuntime",
    "AdkA2aExecutor",
    "build_agent_card_from_yaml",
    "ConfiguredA2aExecutor",
    "DEFAULT_SUB_AGENT_TOOL_INSTRUCTION",
    "AgentBackendType",
    "AgentDescriptor",
    "AgentHealthStatus",
    "AgentInvocationResult",
    "AgentResolver",
    "BaseAgentHandle",
    "DynamicAgentRegistry",
    "HostOrchestrator",
    "InferenceProviderLlmAdapter",
    "LocalA2aAgent",
    "LocalA2AHandle",
    "OrchestrationMode",
    "RemoteA2AHandle",
    "SkillDescriptor",
    "SubAgentInvocationPolicy",
    "SubAgentInvoker",
    "SubAgentToolConfig",
    "build_get_task_request",
    "build_local_a2a_agent",
    "build_message_payload",
    "build_post_request",
    "configured_a2a_runtime",
    "extract_task_id",
    "get_global_agent_registry",
    "local_a2a_orchestration_mode",
    "register_agent_package",
    "run_local_a2a_orchestration",
    "set_local_a2a_orchestration_mode",
    "reset_global_agent_registry",
    "default_instruction_prompt_name",
    "load_agent_instruction",
    "make_sub_agent_tool",
]
